# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do

  desc "Release a new version with a major bump_type"
  lane :major do
  	release("major")
    # add actions here: https://docs.fastlane.tools/actions
  end

  def release(type)
  	# pod_lib_lint(
  	# 	allow_warnings: true,
  	# 	use_libraries: true,
  	# )

  	podspec_name = "BeerPod.podspec"
  	version = version_bump_podspec(path: podspec_name, bump_type: type)
  	increment_version_number(version_number: version)

  	#cocopods
  	git_add
  	git_commit(path: ".", message: "#{version} release")
  	add_git_tag(tag: "#{version}")
  	push_to_git_remote
  	pod_push(
  		allow_warnings: true,
  		use_libraries: true,
  	)
  end
end
